(function(){
'use strict';
function createNoSpendModule(ctx){
  const {qs,esc,iso,getState,save,modal}=ctx; let editId='',logChallengeId='',logDate='',entryEditId='';
  const uid=()=>`nse-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, money=value=>Number(value||0).toFixed(2);
  function summarize(log={}){const entries=Array.isArray(log.entries)?log.entries:null;if(entries){const total=entries.reduce((s,x)=>s+Math.max(0,Number(x.amount)||0),0),necessary=entries.filter(x=>x.necessity==='necessary').reduce((s,x)=>s+Math.max(0,Number(x.amount)||0),0);return {entries,total,necessary,unnecessary:total-necessary,count:entries.length,legacy:false,spent:total>0};}const total=Math.max(0,Number(log.amount)||0),necessary=log.spent&&log.necessary!==false?total:0;return {entries:null,total,necessary,unnecessary:total-necessary,count:log.spent?1:0,legacy:true,spent:log.spent===true};}
  const findChallenge=id=>getState().noSpendChallenges.find(x=>String(x.id)===String(id));
  const findLog=(item,date)=>(item?.logs||[]).find(x=>x.date===date)||null;
  function setNoSpendDays(days){qs('#nsDays').value=days;}
  function openNoSpendEditor(id=''){editId=id;const item=id?findChallenge(id):null;qs('#noSpendModalTitle').textContent=item?'编辑 No Spend Challenge':'新建 No Spend Challenge';qs('#nsTitle').value=item?.title||'';qs('#nsStart').value=item?.startDate||iso(new Date());qs('#nsDays').value=item?.days||30;qs('#nsRules').value=item?.rules||'';qs('#nsAllowed').value=item?.allowed||'';qs('#nsWeeklyReview').value=item?.weeklyReview||'';qs('#nsFinalReview').value=item?.finalReview||'';modal.open('noSpendModal');}
  function closeNoSpendEditor(){modal.close('noSpendModal');}
  function saveNoSpend(){const state=getState(),title=qs('#nsTitle').value.trim()||'No Spend Challenge',startDate=qs('#nsStart').value||iso(new Date()),days=Math.max(1,Number(qs('#nsDays').value)||30),d={title,startDate,days,endDate:iso(new Date(new Date(startDate+'T12:00:00').getTime()+(days-1)*86400000)),rules:qs('#nsRules').value.trim(),allowed:qs('#nsAllowed').value.trim(),weeklyReview:qs('#nsWeeklyReview').value.trim(),finalReview:qs('#nsFinalReview').value.trim(),updatedAt:Date.now()};if(editId)Object.assign(findChallenge(editId),d);else state.noSpendChallenges.push({id:uid(),...d,logs:[],status:'active',createdAt:Date.now()});save();closeNoSpendEditor();render();}
  function deleteNoSpend(id){if(confirm('确定删除这个 No Spend Challenge 吗？')){getState().noSpendChallenges=getState().noSpendChallenges.filter(x=>x.id!==id);save();render();}}
  const currentLog=()=>findLog(findChallenge(logChallengeId),logDate);
  function renderLog(){const log=currentLog(),s=summarize(log||{}),summary=qs('#nsLogSummary'),list=qs('#nsLogEntries');if(!summary||!list)return;summary.innerHTML=`<div class="metric-row compact-metrics"><div class="metric"><b>$${money(s.total)}</b><span>今日消费总额</span></div><div class="metric"><b>${s.count}</b><span>今日共 ${s.count} 笔</span></div><div class="metric"><b>$${money(s.necessary)}</b><span>必要消费</span></div><div class="metric"><b>$${money(s.unnecessary)}</b><span>非必要消费</span></div></div><p class="section-note">今日 No Spend 状态：<b>${s.spent?'已消费':'No Spend'}</b>${s.legacy&&s.count?' · 历史汇总记录':''}</p>`;if(s.legacy&&s.count){list.innerHTML=`<div class="entry"><b>历史消费汇总</b><p>$${money(s.total)} · ${log.necessary===false?'非必要':'必要'}${log.reason?` · ${esc(log.reason)}`:''}</p><small>此历史记录保留原统计，未伪造消费明细。</small></div>`;return;}list.innerHTML=s.entries?.length?s.entries.map(x=>`<article class="entry no-spend-entry" data-no-spend-entry-id="${esc(x.id)}"><button type="button" class="no-spend-entry-main" onclick="editNoSpendEntry('${esc(x.id)}')"><b>${esc(x.merchant||x.category||'消费')}</b><span>$${money(x.amount)} · ${x.necessity==='necessary'?'必要':'非必要'}${x.category&&x.merchant?` · ${esc(x.category)}`:''}${x.note?`<small>${esc(x.note)}</small>`:''}</span></button><button type="button" class="danger icon-action" onclick="deleteNoSpendEntry('${esc(x.id)}')">删除</button></article>`).join(''):'<div class="entry"><span class="small">今天还没有消费明细。</span></div>';}
  function openNoSpendLog(id,date=''){if(!findChallenge(id))return;logChallengeId=id;logDate=date||iso(new Date());qs('#nsLogDate').value=logDate;renderLog();modal.open('noSpendLogModal');}
  function setNoSpendLogDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||'')))return;logDate=String(date);entryEditId='';renderLog();}
  function closeNoSpendLog(){modal.close('noSpendLogModal');}
  function openNoSpendEntry(id=''){if(summarize(currentLog()||{}).legacy&&currentLog()?.spent){alert('历史汇总记录会保留原始统计，不能添加虚构明细。');return;}const row=(currentLog()?.entries||[]).find(x=>x.id===id);entryEditId=id;qs('#nsEntryTitle').textContent=row?'编辑一笔消费':'增加一笔消费';qs('#nsEntryAmount').value=row?.amount??'';qs('#nsEntryNecessity').value=row?.necessity||'necessary';qs('#nsEntryCategory').value=row?.category||'';qs('#nsEntryMerchant').value=row?.merchant||'';qs('#nsEntryNote').value=row?.note||'';modal.push('noSpendLogModal','noSpendEntryModal',{challengeId:logChallengeId,date:logDate});}
  function editNoSpendEntry(id){openNoSpendEntry(id);}
  function closeNoSpendEntry(){entryEditId='';modal.pop('noSpendEntryModal');renderLog();}
  function saveNoSpendEntry(){const item=findChallenge(logChallengeId);if(!item)return;item.logs=Array.isArray(item.logs)?item.logs:[];let log=findLog(item,logDate);if(!log){log={date:logDate,entries:[],createdAt:Date.now()};item.logs.push(log);}if(!Array.isArray(log.entries))log.entries=[];const amount=Math.max(0,Number(qs('#nsEntryAmount').value)||0);if(amount<=0){alert('请输入大于 0 的金额。');return;}const old=log.entries.find(x=>x.id===entryEditId),data={id:entryEditId||uid(),amount,necessity:qs('#nsEntryNecessity').value==='unnecessary'?'unnecessary':'necessary',category:qs('#nsEntryCategory').value.trim(),merchant:qs('#nsEntryMerchant').value.trim(),note:qs('#nsEntryNote').value.trim(),createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()};if(old)Object.assign(old,data);else log.entries.push(data);log.spent=summarize(log).spent;log.updatedAt=Date.now();item.updatedAt=Date.now();save();entryEditId='';modal.pop('noSpendEntryModal');renderLog();render();}
  function deleteNoSpendEntry(id){const item=findChallenge(logChallengeId),log=currentLog();if(!item||!log||!Array.isArray(log.entries)||!confirm('删除这笔消费吗？'))return;log.entries=log.entries.filter(x=>x.id!==id);log.spent=summarize(log).spent;log.updatedAt=Date.now();item.updatedAt=Date.now();save();renderLog();render();}
  function totals(item){return (item.logs||[]).reduce((r,log)=>{const s=summarize(log);r.total+=s.total;r.unnecessary+=s.unnecessary;r.noSpend+=s.spent?0:1;return r;},{total:0,unnecessary:0,noSpend:0});}
  function render(){const el=qs('#noSpendList');if(!el)return;const list=getState().noSpendChallenges.slice().sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));el.innerHTML=list.length?list.map(item=>{const t=totals(item),pct=Math.min(100,Math.round(t.noSpend/Math.max(1,item.days)*100));return `<div class="tool-card" data-challenge-id="${esc(item.id)}"><div class="tool-card-head"><div><h3>${esc(item.title)}</h3><div class="meta">${esc(item.startDate)} → ${esc(item.endDate)} · ${item.days} 天</div></div><span class="status-pill">${t.noSpend}/${item.days} No Spend</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="metric-row"><div class="metric"><b>${money(t.total)}</b><span>已记录消费</span></div><div class="metric"><b>${money(t.unnecessary)}</b><span>非必要消费</span></div></div><div class="tool-actions"><button onclick="openNoSpendLog('${item.id}')">今日记录</button><button onclick="openNoSpendEditor('${item.id}')">编辑</button><button class="danger" onclick="deleteNoSpend('${item.id}')">删除</button></div></div>`;}).join(''):'<div class="entry"><span class="small">还没有 No Spend Challenge。</span></div>';}
  return {render,openNoSpendEditor,closeNoSpendEditor,setNoSpendDays,saveNoSpend,openNoSpendLog,setNoSpendLogDate,closeNoSpendLog,openNoSpendEntry,editNoSpendEntry,closeNoSpendEntry,saveNoSpendEntry,deleteNoSpendEntry,deleteNoSpend,__test:{summarize}};
}
window.JournalModules=window.JournalModules||{};window.JournalModules.createNoSpendModule=createNoSpendModule;
})();
