(function(){
  'use strict';
  function createProductivityModule(ctx){
    const {qs,esc,iso,getState,save,modal}=ctx;let challengeEditId='',twyEditId='',activeCycleId='',activeWeekIndex=0;
    const CHECKBOX_TRACE_KEY='journal-planner-project30-checkbox-trace-v0220';
    let checkboxTrace=(()=>{try{return JSON.parse(localStorage.getItem(CHECKBOX_TRACE_KEY)||'{"events":[]}');}catch(_){return {events:[]};}})();
    function traceCheckbox(step,data={}){const event={at:new Date().toISOString(),step,...data};checkboxTrace.events=[...(checkboxTrace.events||[]),event].slice(-120);try{localStorage.setItem(CHECKBOX_TRACE_KEY,JSON.stringify(checkboxTrace));}catch(_){}return event;}
    function challengeSnapshot(challengeId,date,ruleId){const challenge=getState().challenges.find(item=>String(item.id)===String(challengeId)),log=challenge?.dailyLogs?.[date]||{};return {challengeId,date,ruleId,canonicalValue:log[ruleId],canonicalValueType:typeof log[ruleId],log:JSON.parse(JSON.stringify(log))};}
    const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
    const parseDate=v=>v?new Date(v+'T12:00:00'):new Date();
    const addDays=(v,n)=>{const d=parseDate(v);d.setDate(d.getDate()+n);return iso(d)};
    function normalizeChallenge(c){c.mode=c.mode||'checklist';c.rules=Array.isArray(c.rules)?c.rules:[];c.checklistRules=Array.isArray(c.checklistRules)?c.checklistRules:c.rules.map((title,i)=>typeof title==='string'?{id:`legacy-${i}`,title,required:true,sortOrder:i}:title);c.scoreRules=Array.isArray(c.scoreRules)?c.scoreRules:[];c.dailyLogs=c.dailyLogs&&typeof c.dailyLogs==='object'?c.dailyLogs:{};return c;}
    function normalizeDayLog(log={}){const record=log&&typeof log==='object'?log:{};record.ruleNotes=record.ruleNotes&&typeof record.ruleNotes==='object'?record.ruleNotes:{};record.ruleSnapshots=record.ruleSnapshots&&typeof record.ruleSnapshots==='object'?record.ruleSnapshots:{};if(typeof record.dailyNote!=='string')record.dailyNote=typeof record.dayNote==='string'?record.dayNote:'';delete record.dayNote;return record;}
    function scoreRuleRow(rule={id:uid('rule'),title:'',score:0,kind:'required'}){return `<div class="challenge-rule-row" data-score-rule data-id="${esc(rule.id)}" data-kind="${rule.kind}"><input class="cr-title" placeholder="规则名称" value="${esc(rule.title||'')}"><input class="cr-score" type="number" min="0" max="100" value="${Number(rule.score)||0}" oninput="updateChallengeScoreValidation()"><button type="button" class="danger" onclick="this.closest('[data-score-rule]').remove();updateChallengeScoreValidation()">移除</button></div>`;}
    function renderScoreEditor(rules=[],sort='custom'){const arrange=list=>sort==='score_desc'?[...list].sort((a,b)=>Number(b.score||0)-Number(a.score||0)):sort==='score_asc'?[...list].sort((a,b)=>Number(a.score||0)-Number(b.score||0)):list;const required=arrange(rules.filter(x=>x.kind==='required')),bonus=arrange(rules.filter(x=>x.kind==='bonus'));qs('#challengeRequiredRules').innerHTML=required.map(scoreRuleRow).join('');qs('#challengeBonusRules').innerHTML=bonus.map(scoreRuleRow).join('');updateChallengeScoreValidation();}
    function addChallengeScoreRule(kind){const target=qs(kind==='required'?'#challengeRequiredRules':'#challengeBonusRules');target.insertAdjacentHTML('beforeend',scoreRuleRow({id:uid('rule'),kind,title:'',score:0}));updateChallengeScoreValidation();}
    function readScoreRules(){return [...document.querySelectorAll('[data-score-rule]')].map((row,i)=>({id:row.dataset.id||uid('rule'),title:row.querySelector('.cr-title').value.trim(),score:Math.max(0,Number(row.querySelector('.cr-score').value)||0),kind:row.dataset.kind,sortOrder:i})).filter(x=>x.title);}
    function updateChallengeScoreValidation(){const rules=readScoreRules(),required=rules.filter(x=>x.kind==='required').reduce((n,x)=>n+x.score,0),bonus=Math.max(0,...rules.filter(x=>x.kind==='bonus').map(x=>x.score)),total=required+bonus,el=qs('#challengeScoreValidation');el.textContent=`必须项：${required} · 最高加分：${bonus} · 每日最高：${total} / 100${total===100?' ✓':'（保存前必须等于 100）'}`;el.classList.toggle('validation-error',total!==100);return total;}
    function challengeModeChanged(){const score=qs('#challengeMode').value==='score';qs('#challengeScoreEditor').hidden=!score;qs('#challengeChecklistEditor').hidden=score;if(score)updateChallengeScoreValidation();}
    function setChallengeRuleSort(){const rules=readScoreRules();renderScoreEditor(rules,qs('#challengeRuleSort').value);}
    function setChallengeDays(days){qs('#challengeDays').value=days;}
    function setChallengePreset(type){if(type==='project50'){qs('#challengeTitle').value='Project 50';qs('#challengeDays').value=50;qs('#challengeMode').value='checklist';challengeModeChanged();}}
    function openChallengeEditor(id=''){challengeEditId=id;const c=id?normalizeChallenge(getState().challenges.find(x=>x.id===id)):null;qs('#challengeModalTitle').textContent=c?'编辑 Challenge':'新建 Challenge';qs('#challengeTitle').value=c?.title||'';qs('#challengeStart').value=c?.startDate||iso(new Date());qs('#challengeDays').value=c?.days||50;qs('#challengeMode').value=c?.mode||'checklist';qs('#challengeRules').value=(c?.checklistRules||[]).map(x=>typeof x==='string'?x:x.title).join('\n');let sorter=qs('#challengeRuleSort');if(!sorter){sorter=document.createElement('select');sorter.id='challengeRuleSort';sorter.innerHTML='<option value="custom">自定义顺序</option><option value="score_desc">分数高 → 低</option><option value="score_asc">分数低 → 高</option>';sorter.onchange=setChallengeRuleSort;qs('#challengeScoreEditor').prepend(sorter);}sorter.value=c?.scoreRuleOrder||'custom';renderScoreEditor(c?.scoreRules||[],sorter.value);challengeModeChanged();modal.open('challengeModal');}
    function closeChallengeEditor(){modal.close('challengeModal');}
    function saveChallenge(){const mode=qs('#challengeMode').value,scoreRules=readScoreRules();if(mode==='score'&&updateChallengeScoreValidation()!==100){alert('每日最高分需要等于 100 分。');return;}const title=qs('#challengeTitle').value.trim()||'Focus Challenge',startDate=qs('#challengeStart').value||iso(new Date()),days=Math.max(1,Number(qs('#challengeDays').value)||1),existingChecklist=challengeEditId?normalizeChallenge(getState().challenges.find(x=>x.id===challengeEditId)).checklistRules:[],checklistRules=qs('#challengeRules').value.split('\n').map(x=>x.trim()).filter(Boolean).map((title,i)=>({id:existingChecklist[i]?.id||uid('check'),title,required:true,sortOrder:i})),d={title,startDate,days,endDate:addDays(startDate,days-1),mode,checklistRules,scoreRules,scoreRuleOrder:qs('#challengeRuleSort')?.value||'custom',rules:checklistRules.map(x=>x.title),updatedAt:Date.now()};const state=getState();if(challengeEditId){const c=state.challenges.find(x=>x.id===challengeEditId);Object.assign(c,d);}else state.challenges.push({id:uid('ch'),presetType:title==='Project 50'?'project50':'custom',...d,dailyLogs:{},completedDates:[],status:'active',createdAt:Date.now()});save();closeChallengeEditor();renderChallenges();}
    function calculateScore(rules,log={}){const required=rules.filter(r=>r.kind==='required'&&log[r.id]).reduce((n,r)=>n+Number(r.score||0),0),bonus=Math.max(0,...rules.filter(r=>r.kind==='bonus'&&log[r.id]).map(r=>Number(r.score||0)));return Math.min(100,required+bonus);}
    function dailyScore(challenge,date){const log=normalizeChallenge(challenge).dailyLogs[date]||{};return calculateScore(challenge.scoreRules||[],log);}
    function toggleChallengeToday(id){const c=normalizeChallenge(getState().challenges.find(x=>x.id===id));if(!c)return;const date=iso(new Date());if(c.mode==='score'){openChallengeDay(id,date);return;}const done=c.completedDates||[];const i=done.indexOf(date);if(i>=0)done.splice(i,1);else done.push(date);c.updatedAt=Date.now();save();renderChallenges();}
    function openChallengeNotes(id,date=iso(new Date())){openChallengeDay(id,date);}
    let challengeDayContext=null;
    function updateChallengeDayScore(){if(!challengeDayContext)return;const c=normalizeChallenge(getState().challenges.find(x=>x.id===challengeDayContext.id));const log={};document.querySelectorAll('#challengeDayRules input[type=checkbox]').forEach(input=>{if(input.checked)log[input.value]=true;});const score=calculateScore(c.scoreRules,log);const required=c.scoreRules.filter(r=>r.kind==='required'&&log[r.id]).reduce((n,r)=>n+Number(r.score||0),0);const bonus=Math.max(0,...c.scoreRules.filter(r=>r.kind==='bonus'&&log[r.id]).map(r=>Number(r.score||0)));qs('#challengeDayScore').textContent=`必须项：${required} · 加分项：${bonus}（只取最高） · 今日：${score} / 100`;}
    function toggleChallengeRuleNote(button){const row=button.closest('.challenge-day-rule'),editor=row?.querySelector('[data-rule-note]');if(!editor)return;editor.hidden=!editor.hidden;if(!editor.hidden){editor.focus();editor.selectionStart=editor.value.length;editor.selectionEnd=editor.value.length;}button.textContent=editor.hidden?'＋ 添加备注':'收起备注';}
    function openChallengeDay(id,date=iso(new Date())){const c=normalizeChallenge(getState().challenges.find(x=>x.id===id));if(!c)return;challengeDayContext={id,date};const log=normalizeDayLog(c.dailyLogs[date]);const noteEditor=r=>{const note=log.ruleNotes[r.id]||'';return `<button type="button" class="link-button challenge-note-toggle" onclick="toggleChallengeRuleNote(this)">${note?'编辑备注':'＋ 添加备注'}</button><textarea data-rule-note="${esc(r.id)}" rows="2" ${note?'':'hidden'} placeholder="记录今天具体完成了什么，或未完成的原因">${esc(note)}</textarea>`;};const scoreGroup=(title,rules)=>`<section class="challenge-day-group"><h3>${title}</h3>${rules.map(r=>`<div class="challenge-day-rule"><label><input type="checkbox" data-challenge-rule-id="${esc(r.id)}" value="${esc(r.id)}" ${log[r.id]===true?'checked':''}><span>${esc(r.title||'未命名规则')}</span><b>+${Number(r.score||0)}</b></label>${noteEditor(r)}</div>`).join('')||'<p class="small">暂无规则</p>'}</section>`;const checklistGroup=()=>`<section class="challenge-day-group"><h3>今日规则</h3>${(c.checklistRules||[]).map(r=>`<div class="challenge-day-rule"><label><span>${esc(r.title||'未命名规则')}</span></label>${noteEditor(r)}</div>`).join('')||'<p class="small">暂无规则</p>'}</section>`;qs('#challengeDayTitle').textContent=`${c.title} · ${date}`;const rulesHost=qs('#challengeDayRules');rulesHost.innerHTML=`<label class="challenge-day-date">日期<div class="date-field"><input id="challengeDayDate" type="date" value="${esc(date)}" onchange="setChallengeDayDate(this.value)"></div></label>`+(c.mode==='score'?scoreGroup('必须项',c.scoreRules.filter(r=>r.kind==='required'))+scoreGroup('加分项（每天只取最高一项）',c.scoreRules.filter(r=>r.kind==='bonus')):checklistGroup());window.project30InteractionTraceEditorOpen?.({challengeId:id,title:c.title,mode:c.mode,date,rulesHost,log});if(rulesHost.dataset?.challengeCheckboxBound!=='true'){rulesHost.dataset.challengeCheckboxBound='true';rulesHost.addEventListener?.('change',event=>{const input=event.target?.closest?.('[data-challenge-rule-id]')||event.target;if(!input?.dataset?.challengeRuleId)return;updateChallengeDayScore();recordChallengeCheckboxChange(input);});window.project30InteractionTraceListenerAttached?.({challengeId:id,date,rulesHost,selector:'[data-challenge-rule-id]'});}qs('#challengeDayNote').value=log.dailyNote||'';qs('#challengeDayScore').hidden=c.mode!=='score';if(c.mode==='score')updateChallengeDayScore();traceCheckbox('editor_open',{challengeId:id,date,mode:c.mode,checkboxes:[...document.querySelectorAll('#challengeDayRules input[type=checkbox][data-challenge-rule-id]')].map(input=>({ruleId:input.dataset.challengeRuleId,canonicalChecked:log[input.value]===true,domChecked:input.checked,draftChecked:input.checked}))});modal.open('challengeDayModal');}
    function setChallengeDayDate(date){if(!challengeDayContext||!date)return;openChallengeDay(challengeDayContext.id,date);}
    function closeChallengeDay(){challengeDayContext=null;modal.close('challengeDayModal');}
    function recordChallengeCheckboxChange(input){if(!challengeDayContext||!input?.dataset.challengeRuleId)return;const before=challengeSnapshot(challengeDayContext.id,challengeDayContext.date,input.dataset.challengeRuleId);traceCheckbox('checkbox_change',{challengeId:challengeDayContext.id,date:challengeDayContext.date,ruleId:input.dataset.challengeRuleId,before:before.canonicalValue,domChecked:input.checked,draftBefore:before.canonicalValue===true,draftAfter:input.checked});}
    function saveChallengeDay(){if(!challengeDayContext)return;const c=normalizeChallenge(getState().challenges.find(x=>x.id===challengeDayContext.id)),date=challengeDayContext.date,previous=normalizeDayLog(c.dailyLogs[date]),log={...previous,ruleNotes:{},ruleSnapshots:{}};const inputs=[...document.querySelectorAll('#challengeDayRules input[type=checkbox][data-challenge-rule-id]')];traceCheckbox('save_clicked',{challengeId:c.id,date,mode:c.mode,draft:inputs.map(input=>({ruleId:input.dataset.challengeRuleId,checked:input.checked,valueType:typeof input.checked}))});traceCheckbox('canonical_before_save',challengeSnapshot(c.id,date,inputs[0]?.dataset.challengeRuleId));if(c.mode==='score'){(c.scoreRules||[]).forEach(rule=>{delete log[rule.id];});inputs.forEach(input=>{log[input.value]=input.checked;});}document.querySelectorAll('#challengeDayRules [data-rule-note]').forEach(input=>{const note=input.value.trim(),ruleId=input.dataset.ruleNote;if(note){log.ruleNotes[ruleId]=note;const rule=[...(c.scoreRules||[]),...(c.checklistRules||[])].find(item=>item.id===ruleId);log.ruleSnapshots[ruleId]=rule?.title||previous.ruleSnapshots?.[ruleId]||'已删除的规则';}});const dailyNote=(qs('#challengeDayNote').value||'').trim();if(dailyNote)log.dailyNote=dailyNote;else delete log.dailyNote;delete log.dayNote;c.dailyLogs[date]=log;c.updatedAt=Date.now();traceCheckbox('canonical_after_apply',{challengeId:c.id,date,log:JSON.parse(JSON.stringify(log))});const result=save();traceCheckbox('persistence_result',{challengeId:c.id,date,result:result||{ok:true}});let persisted=null;try{persisted=JSON.parse(localStorage.getItem('journal-planner-v091')||'{}');}catch(error){persisted={readError:String(error)};}const persistedChallenge=(persisted.challenges||[]).find(item=>String(item.id)===String(c.id));traceCheckbox('persisted_read_back',{challengeId:c.id,date,log:persistedChallenge?.dailyLogs?.[date]||null});closeChallengeDay();renderChallenges();}
    function challengeStats(c){normalizeChallenge(c);if(c.mode!=='score'){const done=(c.completedDates||[]).length;return `完成 ${done}/${c.days} 天`; }const scores=Object.keys(c.dailyLogs).map(d=>dailyScore(c,d)),completed=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,elapsed=Math.max(1,Math.min(c.days,Math.floor((Date.now()-parseDate(c.startDate))/86400000)+1)),elapsedAvg=Math.round(scores.reduce((a,b)=>a+b,0)/elapsed);return `今日 ${dailyScore(c,iso(new Date()))}/100 · 已打卡平均 ${completed} · 截至今日 ${elapsedAvg}`;}
    function renderChallenges(){const el=qs('#challengeList');if(!el)return;const list=getState().challenges.map(normalizeChallenge).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));el.innerHTML=list.length?list.map(c=>{const noteDays=Object.values(c.dailyLogs||{}).filter(log=>normalizeDayLog(log).dailyNote).length;return `<div class="tool-card" data-challenge-id="${esc(c.id)}"><div class="tool-card-head"><div><h3>${esc(c.title)}</h3><div class="meta">${esc(c.startDate)} → ${esc(c.endDate)} · ${c.days} 天 · ${c.mode==='score'?'100 分制':'打卡制'}${noteDays?` · 📝 ${noteDays}`:''}</div></div><span class="status-pill">${c.mode==='score'?`${dailyScore(c,iso(new Date()))}/100`:`${(c.completedDates||[]).length}/${c.days}`}</span></div><div class="meta" style="margin-top:6px">${esc(challengeStats(c))}</div><div class="tool-actions"><button onclick="toggleChallengeToday('${c.id}')">${c.mode==='score'?'记录今日分数':'今天打卡'}</button><button onclick="openChallengeNotes('${c.id}')">备注</button><button onclick="openChallengeEditor('${c.id}')">编辑</button><button class="danger" onclick="deleteChallenge('${c.id}')">删除</button></div></div>`;}).join(''):'<div class="entry"><span class="small">还没有 Challenge。</span></div>';}
    function deleteChallenge(id){if(!confirm('确定删除这个 Challenge 吗？'))return;getState().challenges=getState().challenges.filter(x=>x.id!==id);save();renderChallenges();}
    function weekRange(c,i){const s=addDays(c.startDate||iso(new Date()),i*7);return `${s} → ${addDays(s,6)}`;}
    function buildWeeks(c){return `<div class="twy-week-list">${Array.from({length:12},(_,i)=>{const w=c.weeks?.[i]||{},done=!!(w.plan||w.actions||w.review||w.score);return `<button class="twy-week-card" onclick="openTwelveWeekDetail('${c.id}',${i})"><span><b>Week ${i+1}</b><small>${esc(weekRange(c,i))}</small></span><span class="status-pill">${done?`${w.score||0}%`:'待计划'}</span></button>`;}).join('')}</div>`;}
    function openTwelveWeekEditor(id=''){twyEditId=id;const c=id?getState().twelveWeekYears.find(x=>x.id===id):null;qs('#twyTitle').value=c?.title||'';qs('#twyStart').value=c?.startDate||iso(new Date());qs('#twyVision').value=c?.vision||'';qs('#twyGoals').value=(c?.goals||[]).join('\n');qs('#twyWeeks').innerHTML=c?buildWeeks(c):'<div class="entry"><span class="small">保存周期总览后，即可逐周建立计划与复盘。</span></div>';qs('#twyReview').value=c?.review||'';modal.open('twelveWeekModal');}
    function closeTwelveWeekEditor(){modal.close('twelveWeekModal');}
    function saveTwelveWeekYear(){const state=getState(),title=qs('#twyTitle').value.trim()||'12 Week Year',startDate=qs('#twyStart').value||iso(new Date()),d={title,startDate,endDate:addDays(startDate,83),vision:qs('#twyVision').value.trim(),goals:qs('#twyGoals').value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,3),review:qs('#twyReview').value.trim(),updatedAt:Date.now()};if(twyEditId)Object.assign(state.twelveWeekYears.find(x=>x.id===twyEditId),d);else state.twelveWeekYears.push({id:uid('twy'),...d,weeks:Array.from({length:12},()=>({})),status:'active',createdAt:Date.now()});save();closeTwelveWeekEditor();renderTwelveWeekYears();}
    function openTwelveWeekDetail(cycleId,index){const c=getState().twelveWeekYears.find(x=>x.id===cycleId);if(!c)return;activeCycleId=cycleId;activeWeekIndex=index;const w=c.weeks?.[index]||{};qs('#twyWeekTitle').textContent=`Week ${index+1}`;qs('#twyWeekDates').textContent=weekRange(c,index);qs('#twyWeekPlan').value=w.plan||'';qs('#twyWeekActions').value=w.actions||'';qs('#twyWeekScore').value=w.score??'';qs('#twyWeekNotes').value=w.notes||'';qs('#twyWeekReview').value=w.review||'';if(modal.isOpen('twelveWeekModal'))modal.push('twelveWeekModal','twyWeekModal',{flow:'twelve-week-cycle-week-detail'});else modal.open('twyWeekModal');}
    function closeTwelveWeekDetail(){modal.pop('twyWeekModal');}
    function saveTwelveWeekDetail(){const c=getState().twelveWeekYears.find(x=>x.id===activeCycleId);if(!c)return;c.weeks=Array.isArray(c.weeks)?c.weeks:Array.from({length:12},()=>({}));c.weeks[activeWeekIndex]={plan:qs('#twyWeekPlan').value.trim(),actions:qs('#twyWeekActions').value.trim(),score:Math.max(0,Math.min(100,Number(qs('#twyWeekScore').value)||0)),notes:qs('#twyWeekNotes').value.trim(),review:qs('#twyWeekReview').value.trim()};c.updatedAt=Date.now();save();renderTwelveWeekYears();modal.pop('twyWeekModal');if(modal.isOpen('twelveWeekModal'))qs('#twyWeeks').innerHTML=buildWeeks(c);}
    function deleteTwelveWeekYear(id){if(confirm('确定删除这个 12 Week Year 周期吗？')){getState().twelveWeekYears=getState().twelveWeekYears.filter(x=>x.id!==id);save();renderTwelveWeekYears();}}
    function renderTwelveWeekYears(){const el=qs('#twelveWeekList');if(!el)return;el.innerHTML=getState().twelveWeekYears.length?getState().twelveWeekYears.map(c=>`<div class="tool-card"><h3>${esc(c.title)}</h3><div class="meta">${esc(c.startDate)} → ${esc(c.endDate)}</div><div class="tool-actions"><button onclick="openTwelveWeekEditor('${c.id}')">打开周期</button><button class="danger" onclick="deleteTwelveWeekYear('${c.id}')">删除</button></div></div>`).join(''):'<div class="entry"><span class="small">还没有 12 Week Year 周期。</span></div>';}
    function render(){renderChallenges();renderTwelveWeekYears();}
    function clearProject30CheckboxTrace(){checkboxTrace={events:[]};try{localStorage.removeItem(CHECKBOX_TRACE_KEY);}catch(_){}return checkboxTrace;}
    function exportProject30CheckboxTrace(){const payload={exportedAt:new Date().toISOString(),appVersion:window.APP_VERSION,schemaVersion:getState().schemaVersion,events:checkboxTrace.events||[]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='project30-checkbox-save-trace-v0220.json';link.click();URL.revokeObjectURL(link.href);return payload;}
    return {render,openChallengeEditor,closeChallengeEditor,setChallengeDays,setChallengePreset,challengeModeChanged,setChallengeRuleSort,addChallengeScoreRule,updateChallengeScoreValidation,saveChallenge,toggleChallengeToday,openChallengeNotes,openChallengeDay,setChallengeDayDate,closeChallengeDay,saveChallengeDay,updateChallengeDayScore,toggleChallengeRuleNote,recordChallengeCheckboxChange,clearProject30CheckboxTrace,exportProject30CheckboxTrace,deleteChallenge,openTwelveWeekEditor,closeTwelveWeekEditor,saveTwelveWeekYear,deleteTwelveWeekYear,openTwelveWeekDetail,closeTwelveWeekDetail,saveTwelveWeekDetail,__challengeTest:{calculateScore,normalizeDayLog}};
  }
  window.JournalModules=window.JournalModules||{};window.JournalModules.createProductivityModule=createProductivityModule;
})();
