const assert=require('assert'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync(require.resolve('../js/inventory.js'),'utf8'),context={window:{JournalModules:{}},setTimeout,clearTimeout};vm.runInNewContext(source,context);
const sort=context.window.JournalModules.createInventorySortLogic(),useOne=context.window.JournalModules.createInventoryUseOneLogic();
const ordered=items=>Array.from(items).sort(sort.sortItems('added',items)).map(item=>item.id);
let items=[{id:'a',name:'Zulu',quantity:5,createdAt:100,updatedAt:100},{id:'b',name:'Bravo',quantity:4,createdAt:200,updatedAt:200},{id:'c',name:'Alpha',quantity:3,createdAt:300,updatedAt:300}];
assert.deepStrictEqual(ordered(items),['a','b','c']);
items[1]={...items[1],updatedAt:999,location:'Shelf',notes:'edited'};assert.deepStrictEqual(ordered(items),['a','b','c']);
let state={schemaVersion:12,inventory:{items:items.map(item=>({...item,history:[]}))}},used=useOne.stageUseOne(state,'b',1000);assert(used.ok);state=used.candidate;assert.deepStrictEqual(ordered(state.inventory.items),['a','b','c']);
const undone=useOne.stageUndo(state,{itemId:'b',previousQuantity:4,nextQuantity:3},1100);assert(undone.ok);assert.deepStrictEqual(ordered(undone.candidate.inventory.items),['a','b','c']);
assert.deepStrictEqual(items.slice().sort(sort.sortItems('updated',items)).map(item=>item.id),['b','c','a']);
assert.deepStrictEqual(items.slice().sort(sort.sortItems('az',items)).map(item=>item.id),['c','b','a']);
assert.deepStrictEqual(items.slice().sort(sort.sortItems('quantityAsc',items)).map(item=>item.id),['c','b','a']);
const legacy=[{id:'old-a',name:'A',quantity:1},{id:'new',name:'New',quantity:1,createdAt:500},{id:'old-b',name:'B',quantity:1}];
assert.deepStrictEqual(ordered(legacy),['new','old-a','old-b']);assert.deepStrictEqual(ordered(JSON.parse(JSON.stringify(legacy))),['new','old-a','old-b']);
assert(sort.validSort('added'));assert(!sort.validSort('unknown'));
const index=fs.readFileSync(require.resolve('../index.html'),'utf8'),app=fs.readFileSync(require.resolve('../js/app.js'),'utf8'),inventory=fs.readFileSync(require.resolve('../js/inventory.js'),'utf8');
assert(index.includes('option value="added">添加顺序'));
assert(index.includes('onchange="setInventorySort(this.value)"'));
assert(app.includes("inventorySortMode:'added'"));assert(app.includes('state.settings.inventorySortMode=INVENTORY_SORT_MODES.includes'));
assert(inventory.includes('function setSort(mode)'));assert(inventory.includes('list.sort(sortItems(sort,state.items))'));
console.log('Inventory stable sort: 19 assertions passed.');
