const assert=require('assert'),fs=require('fs'),vm=require('vm');
const index=fs.readFileSync(require.resolve('../index.html'),'utf8'),styles=fs.readFileSync(require.resolve('../styles.css'),'utf8'),inventory=fs.readFileSync(require.resolve('../js/inventory.js'),'utf8'),app=fs.readFileSync(require.resolve('../js/app.js'),'utf8');
assert(index.includes('id="inventoryUseOneSnackbar"'));
assert(!inventory.includes('inventory-use-one-notice'));
assert(inventory.includes('renderUseOneSnackbar()'));
assert(inventory.includes('setTimeout(()=>{useOneUndo=null;useOneNotice=null;render();},8000)'));
assert(styles.includes('.inventory-use-one-snackbar{position:fixed'));
assert(styles.includes('bottom:calc(var(--bottom-nav-space) + env(safe-area-inset-bottom) + 10px)'));
assert(styles.includes('z-index:22'));
assert(styles.includes('.inventory-use-one-snackbar[hidden]{display:none}'));
assert(app.includes('PersistenceFoundation?.commitCanonical'));
assert(app.includes('Number(persisted.schemaVersion)!==12'));
const source=fs.readFileSync(require.resolve('../js/inventory.js'),'utf8'),context={window:{JournalModules:{}},setTimeout,clearTimeout};vm.runInNewContext(source,context);
const logic=context.window.JournalModules.createInventoryUseOneLogic();
let state={schemaVersion:12,inventory:{items:[{id:'a',quantity:5,history:[]},{id:'b',quantity:3,history:[]}]}};
const a=logic.stageUseOne(state,'a',1000);state=a.candidate;const b=logic.stageUseOne(state,'b',2000);state=b.candidate;
const undoB=logic.stageUndo(state,{itemId:b.itemId,previousQuantity:b.previousQuantity,nextQuantity:b.nextQuantity},3000);
assert(undoB.ok);assert.strictEqual(undoB.candidate.inventory.items.find(item=>item.id==='a').quantity,4);assert.strictEqual(undoB.candidate.inventory.items.find(item=>item.id==='b').quantity,3);
const failedUndoState=JSON.stringify(state);assert(undoB.ok);assert.strictEqual(JSON.stringify(state),failedUndoState);
console.log('Inventory snackbar: 15 assertions passed.');
